### ISSUE TITLE
Search for Perl 6 modules **only** ?

### ISSUE THREAD

**Issue by lizmat** [charsbar/CPAN-Groonga#1]
Would it be possible to add a radio button / check box to indicate that you're interested in Perl 6 modules only?

**Comment by charsbar** [comment]
Well, it's already there (click "Advanced options", then check "pm6" checkbox). Might it be better not to hide those options?

**Comment by lizmat** [comment]
The thing is that many Perl 6 modules actually use the .pm and .pl prefixes (as originally specced).  So selecting .pm6 / .pl6 does *not* guarantee that you see all possible Perl 6 files.  Whereas also selecting .pm guarantees you that you *will* see files that are *not* Perl 6.

**Comment by charsbar** [comment]
It turns out that some of the contents (author, snippet, and maybe more) of the records of distributions that both Perl 5 and Perl 6 have are mingled. Will fix it this weekend. Sorry for the inconvenience.

**Comment by charsbar** [comment]
Now I think I've fixed this issue. I recreated the whole database. Please let me know if you still find something wrong.

**Comment by lizmat** [comment]
Thanks!
